version: '3.8'

services:
  webapi:
    image: flightapp-api
    build:
      context: ./src/FlightManagement.API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=FlightAppDb;User=sa;Password=YourStrongPassword;
